name: sensor-examples
version: 0
binaries:
  sensor-temp-pcsensor:
    exec: usr/local/bin/pcsensor
summary: sensor examples
description: a set of sensor examples for snappy
icon: icon.png

parts:
  pcsensor:
    plugin: make
    source: git://github.com/asac/usb-thermometer

