name: sensor-examples
version: 0
binaries:
  sensor-temp-pcsensor:
    exec: usr/local/bin/pcsensor
  lm-sensors:
    exec: usr/bin/sensors
  vmstat:
    exec: usr/bin/vmstat
summary: sensor examples
description: a set of sensor examples for snappy
icon: icon.png
vendor: Alexander Sack <asac@canonical.com>
build-packages:
  - libudev-dev

parts:
  pcsensor:
    plugin: make
    source: git://github.com/asac/usb-thermometer
  lm-sensors:
    stage-packages: [ lm-sensors ]
    plugin: make
    source: ./lm-sensors
  vmstat:
    plugin: copy
    source: ./vmstat
    files:
      vmstat/vmstat: usr/bin/vmstat
  openzwave:
    plugin: make
    source: git://github.com/asac/open-zwave
#  openzwave-control-panel:
#    plugin: make
#    source: git://github.com/OpenZWave/open-zwave-control-panel
#    after: [ openzwave ]

